#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : statsmodels
Version  : 0.13.0
Release  : 23
URL      : https://files.pythonhosted.org/packages/9e/5e/4a2ade283411d1f46d6f8dd5fe951b9152062d55a20750cd5d4b556322bf/statsmodels-0.13.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/9e/5e/4a2ade283411d1f46d6f8dd5fe951b9152062d55a20750cd5d4b556322bf/statsmodels-0.13.0.tar.gz
Summary  : Statistical computations and models for Python
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: statsmodels-license = %{version}-%{release}
Requires: statsmodels-python = %{version}-%{release}
Requires: statsmodels-python3 = %{version}-%{release}
Requires: Cython
Requires: numpy
Requires: pandas
Requires: patsy
Requires: scipy
BuildRequires : Cython
BuildRequires : buildreq-distutils3
BuildRequires : nose
BuildRequires : numpy
BuildRequires : pandas
BuildRequires : patsy
BuildRequires : pytest
BuildRequires : python-dateutil
BuildRequires : scipy

%description
The format for landing.json should be self-explanatory. The images should be placed in docs/source/_static/images/. They will be displayed at 360 x 225 (W x H). It's best to save them as a png with a resolution of a multiple of at least 720 x 450. If you want, you can use png crush to make the images smaller.

%package license
Summary: license components for the statsmodels package.
Group: Default

%description license
license components for the statsmodels package.


%package python
Summary: python components for the statsmodels package.
Group: Default
Requires: statsmodels-python3 = %{version}-%{release}

%description python
python components for the statsmodels package.


%package python3
Summary: python3 components for the statsmodels package.
Group: Default
Requires: python3-core

%description python3
python3 components for the statsmodels package.


%prep
%setup -q -n statsmodels-0.13.0
cd %{_builddir}/statsmodels-0.13.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636482876
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

## build_append content
rm -f %{_builddir}/statsmodels-0.13.0/statsmodels/LICENSE.txt
touch  %{_builddir}/statsmodels-0.13.0/statsmodels/LICENSE.txt
## build_append end
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/statsmodels
cp %{_builddir}/statsmodels-0.13.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/statsmodels/2d60e5640eefa748369bb8731e2376c1993cca43
cp %{_builddir}/statsmodels-0.13.0/statsmodels/LICENSE.txt %{buildroot}/usr/share/package-licenses/statsmodels/2d60e5640eefa748369bb8731e2376c1993cca43
cp %{_builddir}/statsmodels-0.13.0/statsmodels/multivariate/factor_rotation/LICENSE.txt %{buildroot}/usr/share/package-licenses/statsmodels/0fc2c72f519bbfc29403c0fea97ec8f2dc28b35a
cp %{_builddir}/statsmodels-0.13.0/statsmodels/stats/libqsturng/LICENSE.txt %{buildroot}/usr/share/package-licenses/statsmodels/c207c94132c3d588103b506d0eeec17c665c0ae6
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/statsmodels/0fc2c72f519bbfc29403c0fea97ec8f2dc28b35a
/usr/share/package-licenses/statsmodels/2d60e5640eefa748369bb8731e2376c1993cca43
/usr/share/package-licenses/statsmodels/c207c94132c3d588103b506d0eeec17c665c0ae6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
