#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : statsmodels
Version  : 0.10.1
Release  : 7
URL      : https://files.pythonhosted.org/packages/d3/7d/4f1f18ad782d6b913aeff17d553859fed40751ecf15ef698c69811e622e6/statsmodels-0.10.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/d3/7d/4f1f18ad782d6b913aeff17d553859fed40751ecf15ef698c69811e622e6/statsmodels-0.10.1.tar.gz
Summary  : Statistical computations and models for Python
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause BSD-3-Clause-Clear
Requires: statsmodels-license = %{version}-%{release}
Requires: statsmodels-python = %{version}-%{release}
Requires: statsmodels-python3 = %{version}-%{release}
Requires: Cython
Requires: numpy
Requires: pandas
Requires: patsy
Requires: scipy
BuildRequires : Cython
BuildRequires : buildreq-distutils3
BuildRequires : nose
BuildRequires : numpy
BuildRequires : pandas
BuildRequires : patsy
BuildRequires : pytest
BuildRequires : python-dateutil
BuildRequires : scipy

%description
The format for landing.json should be self-explanatory. The images should be placed in docs/source/_static/images/. They will be displayed at 360 x 225 (W x H). It's best to save them as a png with a resolution of a multiple of at least 720 x 450. If you want, you can use png crush to make the images smaller.

%package license
Summary: license components for the statsmodels package.
Group: Default

%description license
license components for the statsmodels package.


%package python
Summary: python components for the statsmodels package.
Group: Default
Requires: statsmodels-python3 = %{version}-%{release}

%description python
python components for the statsmodels package.


%package python3
Summary: python3 components for the statsmodels package.
Group: Default
Requires: python3-core

%description python3
python3 components for the statsmodels package.


%prep
%setup -q -n statsmodels-0.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570910855
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/statsmodels
cp docs/sphinxext/LICENSE.txt %{buildroot}/usr/share/package-licenses/statsmodels/docs_sphinxext_LICENSE.txt
cp statsmodels/datasets/COPYING %{buildroot}/usr/share/package-licenses/statsmodels/statsmodels_datasets_COPYING
cp statsmodels/stats/libqsturng/LICENSE.txt %{buildroot}/usr/share/package-licenses/statsmodels/statsmodels_stats_libqsturng_LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
/usr/LICENSE.txt
/usr/setup.cfg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/statsmodels/docs_sphinxext_LICENSE.txt
/usr/share/package-licenses/statsmodels/statsmodels_datasets_COPYING
/usr/share/package-licenses/statsmodels/statsmodels_stats_libqsturng_LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
